spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/micromall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 20001218
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true


  jackson:
    property-naming-strategy : CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
#    default-property-inclusion: non_null
server:
  port: 8080
  servlet:
    context-path:
    session:
      timeout: 36000
logging:
  level:

    root: warn
    com.example.micromall.repository: trace
  pattern:
    console: '%p%m%n'


spring.jpa.properties.hibernate.use_sql_comments: true
spring.jpa.properties.hibernate.format_sql: true